"""add cascade delete on user_id and program_id FKs

Revision ID: 43f606a12111
Revises: 863d5948f39d
Create Date: 2026-08-31 20:42:16.976518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f606a12111'
down_revision: Union[str, None] = '863d5948f39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email_verification_tokens_user_id_fkey', 'email_verification_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'email_verification_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('password_reset_tokens_user_id_fkey', 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('program_exercises_program_id_fkey', 'program_exercises', type_='foreignkey')
    op.create_foreign_key(None, 'program_exercises', 'programs', ['program_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('programs_user_id_fkey', 'programs', type_='foreignkey')
    op.create_foreign_key(None, 'programs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'programs', type_='foreignkey')
    op.create_foreign_key('programs_user_id_fkey', 'programs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'program_exercises', type_='foreignkey')
    op.create_foreign_key('program_exercises_program_id_fkey', 'program_exercises', 'programs', ['program_id'], ['id'])
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key('password_reset_tokens_user_id_fkey', 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'email_verification_tokens', type_='foreignkey')
    op.create_foreign_key('email_verification_tokens_user_id_fkey', 'email_verification_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
