"""add injuries and exercise_injuries tables

Revision ID: f57786af1f9d
Revises: a961a1521931
Create Date: 2026-08-25 16:59:58.709925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f57786af1f9d'
down_revision: Union[str, None] = 'a961a1521931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exercise_injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('injury_id', sa.Integer(), nullable=False),
    sa.Column('effectiveness', sa.Integer(), nullable=False),
    sa.CheckConstraint('effectiveness >= 1 AND effectiveness <= 5', name='ck_effectiveness_range'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['injury_id'], ['injuries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'injury_id', name='uq_exercise_injury')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_injuries')
    op.drop_table('injuries')
    # ### end Alembic commands ###
