"""add exercise content fields, drop description

Revision ID: f6b5927eb85a
Revises: f57786af1f9d
Create Date: 2026-08-27 03:39:13.889161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6b5927eb85a'
down_revision: Union[str, None] = 'f57786af1f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('exercises', sa.Column('diagram_url', sa.String(length=500), nullable=True))
    op.add_column('exercises', sa.Column('frequency', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('equipment', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.add_column('exercises', sa.Column('instructions', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.add_column('exercises', sa.Column('common_mistakes', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.add_column('exercises', sa.Column('modification_beginner', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('modification_intermediate', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('modification_advanced', sa.Text(), nullable=True))
    op.drop_column('exercises', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('exercises', 'modification_advanced')
    op.drop_column('exercises', 'modification_intermediate')
    op.drop_column('exercises', 'modification_beginner')
    op.drop_column('exercises', 'common_mistakes')
    op.drop_column('exercises', 'instructions')
    op.drop_column('exercises', 'equipment')
    op.drop_column('exercises', 'frequency')
    op.drop_column('exercises', 'diagram_url')
    op.drop_column('exercises', 'video_url')
    # ### end Alembic commands ###
